name: Groovy Scripts

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  groovy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: download groovy src
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: |
          git clone https://gitbox.apache.org/repos/asf/groovy.git
        
      - name: bootstrap and build
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: |
          cd groovy
          gradle -p bootstrap
          ./gradlew clean dist
          chmod +x groovy/src/bin/groovysh
          ./groovy/src/bin/groovysh


  
