name: Groovy install + script

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  groovy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: download groovy src
        run: |
          curl -O https://dlcdn.apache.org/groovy/4.0.21/distribution/apache-groovy-binary-4.0.21.zip
          unzip apache-groovy-binary-4.0.21.zip
          ls groovy-4.0.21/bin/
          chmod +x groovy-4.0.21/bin/groovy
          
      - name: run script
        run: |
          ./groovy-4.0.21/bin/groovy script.groovy


  
