name: Groovy binary install

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  groovy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: download groovy src
        run: |
          curl -O https://dlcdn.apache.org/groovy/4.0.21/distribution/apache-groovy-binary-4.0.21.zip
          unzip apache-groovy-binary-4.0.21.zip
          mkdir /tmp
          mv groovy-4.0.2 /tmp/groovy/
          ln -s /usr/share/groovy/groovy-4.0.2 current
          
      - name: set groovy home
        run: |
          export GROOVY_HOME=/tmp/groovy/current
          export PATH=$GROOVY_HOME/bin:$PATH

          groovy -version

        
      # - name: bootstrap and build
      #   if: steps.restore-cache.outputs.cache-hit != 'true'
      #   run: |
      #     cd groovy
      #     gradle -p bootstrap
      #     ./gradlew clean dist
      #     chmod +x groovy/src/bin/groovysh
      #     ./groovy/src/bin/groovysh


  
